<a href="https://colab.research.google.com/github/Gayathiri-E/DL/blob/main/DL_NN_code_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.array(([1,0,1,0],[1,0,1,1],[0,1,0,1]))

In [ ]:
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [ ]:
y=np.array(([1],[0],[1]))
y

array([[1],
       [0],
       [1]])

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
def derivative_sigmoid(x):
  return x*(1-x)

In [ ]:
epoch=5000
lr = 0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [ ]:
wh = np.random.uniform(size=(input_neurons,hidden_neurons))
#uniform--input ku thaguntha mari random ah values ah eduthkum for weights and bias in hidden and output
bh = np.random.uniform(size=(1,hidden_neurons))
wo = np.random.uniform(size=(hidden_neurons,output_neurons))
bo = np.random.uniform(size=(1,output_neurons))

In [ ]:
for i in range(epoch):
  #same as single layer perceptron
  #forward propogation
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)

  #backward propagation
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr

In [ ]:
output

array([[0.95389792],
       [0.06113226],
       [0.96703314]])

In [ ]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
x = iris.data
y = iris.target.reshape(-1, 1)  # Reshape to a column vector

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def derivative_sigmoid(x):
    return x * (1 - x)

epoch = 5000
lr = 0.1  # learning_rate
input_neurons = x.shape[1]
hidden_neurons = 2
output_neurons = 1

# Initialize weights and biases
wh = np.random.uniform(size=(input_neurons, hidden_neurons))
bh = np.zeros((1, hidden_neurons))
wo = np.random.uniform(size=(hidden_neurons, output_neurons))
bo = np.zeros((1, output_neurons))

# This coding is the same as Perceptron in Machine Learning
for i in range(epoch):
    # Forward Propagation
    hidden_input = np.dot(x, wh) + bh
    hidden_activation = sigmoid(hidden_input)
    output_layer = np.dot(hidden_activation, wo) + bo
    output = sigmoid(output_layer)

    # Backward Propagation
    E = y - output  # Error: target - predicted
    slope_output = derivative_sigmoid(output)
    slope_hidden = derivative_sigmoid(hidden_activation)

    d_output = E * slope_output
    error_hidden = d_output.dot(wo.T)
    d_hidden = error_hidden * slope_hidden

    wo += np.dot(hidden_activation.T, d_output) * lr
    bo += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += np.dot(x.T, d_hidden) * lr
    bh += np.sum(d_hidden, axis=0, keepdims=True) * lr

In [ ]:
output

array([[0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.999546],
       [0.99

IRIS DATASET

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

# Load the Iris dataset using datasets library
iris = load_iris()
iris_data = pd.DataFrame(data=np.c_[iris['data'], iris['target']], columns=iris['feature_names'] + ['target'])

# Map target classes to numerical values
class_mapping = {0: 0, 1: 1, 2: 2}
iris_data['target'] = iris_data['target'].map(class_mapping)

# Extract features and labels
X = iris_data.iloc[:, :-1].values
y = iris_data.iloc[:, -1].values.reshape(-1, 1)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features (optional but recommended)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def derivative_sigmoid(x):
    return x * (1 - x)

# Define neural network architecture
input_neurons = X_train.shape[1]
hidden_neurons = 8
output_neurons = len(np.unique(y_train))

wh = np.random.uniform(size=(input_neurons, hidden_neurons))
bh = np.random.uniform(size=(1, hidden_neurons))
wo = np.random.uniform(size=(hidden_neurons, output_neurons))
bo = np.random.uniform(size=(1, output_neurons))

# Training parameters
lr = 0.1
epochs = 1500

# Training the neural network
for epoch in range(epochs):
    # Forward propagation
    hidden_input = np.dot(X_train, wh)
    hidden_input += bh
    hidden_activation = sigmoid(hidden_input)
    output_layer = np.dot(hidden_activation, wo)
    output = sigmoid(output_layer)

    # Backward propagation
    E = y_train - output
    slope_output = derivative_sigmoid(output)
    slope_hidden = derivative_sigmoid(hidden_activation)
    d_output = E * slope_output
    error_hidden = d_output.dot(wo.T)
    d_hidden = error_hidden * slope_hidden

    # Update weights and biases
    wo += hidden_activation.T.dot(d_output) * lr
    bo += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += X_train.T.dot(d_hidden) * lr
    bh += np.sum(d_hidden, axis=0, keepdims=True) * lr

    # Print mean squared error for every 100 epochs
    if (epoch + 1) % 100 == 0:
        mse = np.mean((y_train - output) ** 2)
        print(f"Epoch {epoch + 1}/{epochs}, Mean Squared Error: {mse}")

# Testing the neural network
hidden_input_test = np.dot(X_test, wh) + bh
hidden_activation_test = sigmoid(hidden_input_test)
output_layer_test = np.dot(hidden_activation_test, wo) + bo
output_test = sigmoid(output_layer_test)

# Convert output to predicted labels
y_pred = np.argmax(output_test, axis=1)

# Convert one-hot encoded predictions to class labels
y_pred = np.argmax(output_test, axis=1)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


Epoch 100/1500, Mean Squared Error: 0.3257287227226545
Epoch 200/1500, Mean Squared Error: 0.3253195907489713
Epoch 300/1500, Mean Squared Error: 0.3252015614258443
Epoch 400/1500, Mean Squared Error: 0.325146162247291
Epoch 500/1500, Mean Squared Error: 0.3251141846456181
Epoch 600/1500, Mean Squared Error: 0.3250934531601078
Epoch 700/1500, Mean Squared Error: 0.32507896689218274
Epoch 800/1500, Mean Squared Error: 0.32506829767740986
Epoch 900/1500, Mean Squared Error: 0.32506012635483006
Epoch 1000/1500, Mean Squared Error: 0.32505367577063277
Epoch 1100/1500, Mean Squared Error: 0.32504845907567187
Epoch 1200/1500, Mean Squared Error: 0.3250441561838758
Epoch 1300/1500, Mean Squared Error: 0.32504054825955675
Epoch 1400/1500, Mean Squared Error: 0.3250374807718628
Epoch 1500/1500, Mean Squared Error: 0.32503484158612417
Accuracy: 90.00%
